### PR TITLE
Fix join on state for ofec_sched_a_aggregate_state_recipient_totals_mv

### LINKED ISSUE #3142: Schedule A aggregate by state incorrect
Thank you @fecjjeng and @ChingKuan for catching this!

`ofec_sched_a_aggregate_state_recipient_totals_mv` is joining on "state = fips code", resulting in the /schedule_a/by_state/totals/ endpoint returning incorrect results: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/totals/?sort=cycle&per_page=20&api_key=DEMO_KEY&page=1

```
WHERE (agg_st.state::text IN (SELECT fips_state_code
                   FROM staging.ref_zip_to_district))
``` 

should be (typo is in the table)

```
WHERE (agg_st.state::text IN (SELECT **state_abbrevation**
                   FROM staging.ref_zip_to_district))
``` 
- [x] make a new migration for `ofec_sched_a_aggregate_state_recipient_totals_mv`

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

- Resolves #3142 

`ofec_sched_a_aggregate_state_recipient_totals_mv` is joining on "state = fips code", resulting in the /schedule_a/by_state/totals/ endpoint returning incorrect results: https://api.open.fec.gov/v1/schedules/schedule_a/by_state/totals/?sort=cycle&per_page=20&api_key=DEMO_KEY&page=1

```
WHERE (agg_st.state::text IN (SELECT fips_state_code
                   FROM staging.ref_zip_to_district))
``` 

should be (typo is in the table)

```
WHERE (agg_st.state::text IN (SELECT **state_abbrevation**
                   FROM staging.ref_zip_to_district))
``` 
## How to test the changes locally

- test the view by dropping/creating `cfdm_test` and running `invoke create_sample_db` I also ran the script on the `dev` DB and it worked.

## Impacted areas of the application
List general components of the application that this PR will affect:

-  https://api.open.fec.gov/v1/schedules/schedule_a/by_state/totals/?sort=cycle&per_page=20&api_key=DEMO_KEY&page=1
- I'm not sure this is used on the front end yet, but it looks like this is what's going to use it eventually: https://www.fec.gov/data/raising/

### CODE REVIEW

**Comment by fecjjeng** [comment]
This MV has all the fields indexed.  However, the endpoint this MV supported 
https://api.open.fec.gov/v1/schedules/schedule_a/by_state/totals/?sort=cycle&per_page=20&api_key=DEMO_KEY&page=1
has the following input fields: state, cycle, committee_type.  
The fields committee_type_full, state_full, count, total are output columns, will not appear in the where clause and therefore no need to be indexed.  

The index name ofec_sched_a_aggregate_state_recipient__committee_type_idx has an extra "_" between recipient and committee.

The above are pre-existing conditions that is not related to the issue this PR is addressing.  Since we were talking about cleaning up the the MVs, it would be nice to clean it up.

File: data/migrations/V0083__fix_ofec_sched_a_aggregate_state_recipient_totals_mv.sql [hunk 1]
```diff
@@ -0,0 +1,175 @@
+-- Superceeds Migration #54
+-- redefine MATERIALIZED VIEW public.ofec_sched_a_aggregate_state_recipient_totals_mv to join properly to staging.ref_zip_to_district
+
+REFRESH MATERIALIZED VIEW public.ofec_committee_history_mv;
+REFRESH MATERIALIZED VIEW public.ofec_committee_detail_mv;
+
```
Comment (hcaofec) [inline data/migrations/V0083__fix_ofec_sched_a_aggregate_state_recipient_totals_mv.sql]: Tested locally and it looks good.
Line 4 and line 5 may not be necessary since these two materialized views are refreshed every day.

**Comment by fecjjeng** [comment]
Line 4 and Line 5 were needed before the initial migration scripts for all MVs were defined "WITH NO DATA".  Without these two lines, this MV can not be created "WITH DATA" during the test procedure.  However, since those initial migration scripts had been updated, these two lines are not necessary anymore.
